### ISSUE TITLE
`add_metadata_event_struct` causes segmentation fault immediately

### ISSUE THREAD

**Issue by mkaivs** [RidgeRun/gst-shark#117] opened 2022-10-19 23:30 UTC
I built and installed gst-shark on Ubuntu 20.04 as follow:

```
sudo apt install graphviz libgraphviz-dev
sudo apt install octave epstool babeltrace
sudo apt install gtk-doc-tools
git clone https://github.com/RidgeRun/gst-shark/
cd gst-shark
./autogen.sh --prefix /usr/ --libdir /usr/lib/x86_64-linux-gnu/
make
sudo make install
```
This issue doesn't occur when I build from this tag: https://github.com/RidgeRun/gst-shark/tree/v0.6.0. The issue occurred when I use the current master branch.

Then environment variables are: `GST_SHARK_FILE_BUFFERING=0`, `GST_DEBUG="GST_TRACER:7"`, `GST_TRACERS="interlatency"`

The output:

```
0:00:00.003817115 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:171:gst_tracer_register:<tracerfactory0> new tracer factory for cpuusage
0:00:00.003859069 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:178:gst_tracer_register:<cpuusage> tracer factory for 1939735280:GstCPUUsageTracer
0:00:00.003879057 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:171:gst_tracer_register:<tracerfactory1> new tracer factory for graphic
0:00:00.003890783 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:178:gst_tracer_register:<graphic> tracer factory for 1939741872:GstGraphicTracer
0:00:00.003915378 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:171:gst_tracer_register:<tracerfactory2> new tracer factory for proctime
0:00:00.003931716 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:178:gst_tracer_register:<proctime> tracer factory for 1939743232:GstProcTimeTracer
0:00:00.003954616 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:171:gst_tracer_register:<tracerfactory3> new tracer factory for interlatency
0:00:00.003965952 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:178:gst_tracer_register:<interlatency> tracer factory for 1939744192:GstInterLatencyTracer
0:00:00.003986165 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:171:gst_tracer_register:<tracerfactory4> new tracer factory for scheduletime
0:00:00.003997444 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:178:gst_tracer_register:<scheduletime> tracer factory for 1939745216:GstScheduletimeTracer
0:00:00.004017877 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:171:gst_tracer_register:<tracerfactory5> new tracer factory for framerate
0:00:00.004029255 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:178:gst_tracer_register:<framerate> tracer factory for 1939745904:GstFramerateTracer
0:00:00.004057913 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:171:gst_tracer_register:<tracerfactory6> new tracer factory for queuelevel
0:00:00.004070310 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:178:gst_tracer_register:<queuelevel> tracer factory for 1939747008:GstQueueLevelTracer
0:00:00.004184766 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:171:gst_tracer_register:<tracerfactory7> new tracer factory for bitrate
0:00:00.004203239 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:178:gst_tracer_register:<bitrate> tracer factory for 1939747424:GstBitrateTracer
0:00:00.004234651 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:171:gst_tracer_register:<tracerfactory8> new tracer factory for buffer
0:00:00.004247250 35366 0x55e7739d6a90 DEBUG             GST_TRACER gsttracer.c:178:gst_tracer_register:<buffer> tracer factory for 1939751584:GstBufferTracer
0:00:00.103018326 35362 0x56471f920800 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x56471fb70be0 (cpuusage)
0:00:00.103047619 35362 0x56471f920800 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x56471fb70b20 (graphic)
0:00:00.103057431 35362 0x56471f920800 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x56471fb70a60 (proctime)
0:00:00.103065573 35362 0x56471f920800 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x56471fb709a0 (interlatency)
0:00:00.103073369 35362 0x56471f920800 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x56471fb708e0 (scheduletime)
0:00:00.103083432 35362 0x56471f920800 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x56471fb70820 (framerate)
0:00:00.103091245 35362 0x56471f920800 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x56471f92aef0 (queuelevel)
0:00:00.103100717 35362 0x56471f920800 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x56471f92ae30 (bitrate)
0:00:00.103108526 35362 0x56471f920800 DEBUG             GST_TRACER gsttracer.c:161:gst_tracer_register:<registry0> update existing feature 0x56471f92ad70 (buffer)
0:00:00.103163260 35362 0x56471f920800 TRACE             GST_TRACER gsttracerrecord.c:111:gst_tracer_record_build_format: interlatency.class, from_pad=(structure)"scope\,\ type\=\(type\)gchararray\,\ related-to\=\(GstTracerValueScope\)GST_TRACER_VALUE_SCOPE_PAD\;", to_pad=(structure)"scope\,\ type\=\(type\)gchararray\,\ related-to\=\(GstTracerValueScope\)GST_TRACER_VALUE_SCOPE_PAD\;", time=(structure)"scope\,\ type\=\(type\)gchararray\,\ related-to\=\(GstTracerValueScope\)GST_TRACER_VALUE_SCOPE_PROCESS\;";
0:00:00.103177431 35362 0x56471f920800 DEBUG             GST_TRACER gsttracerrecord.c:125:gst_tracer_record_build_format: new format string: interlatency, from_pad=(string)%s, to_pad=(string)%s, time=(string)%s;
Segmentation fault (core dumped)
```
The trace:

![bug_report](https://user-images.githubusercontent.com/72578457/196823433-19774291-dfc6-46bd-a45b-8ca2d41c436f.png)

`add_metadata_event_struct` is the function that caused the Segmentation fault.

The issue can be reproduced by running this command:

```
GST_DEBUG="GST_TRACER:7" GST_TRACERS="interlatency" gst-launch-1.0 videotestsrc ! queue ! videorate max-rate=15 ! fakesink sync=true
```

**Comment by alehed** [comment] 2022-11-16 10:50
I can reproduce this issue. Currently interlatency, proctime, queuelevel and scheduletime are unusable due to this. framerate, cputime and bitrate seem to work.

**Comment by vebjornjr** [comment] 2023-01-19 10:13
I get the same behaviour on Ubuntu 18.04. The fix from @MichaelOultram-pexip seems to work, thank you!

**Comment by jh-aug** [comment] 2023-01-24 11:25
I had the same problem on Xavier NX running Ubuntu 20.04 with Nvidia patches on Gstreamer 1.16.3. Great find by @MichaelOultram-pexip fixed the issue for me. Many thanks!

**Comment by michaelgruner** [comment] 2023-01-25 22:17
Hey all, thanks for the reports and fixes! Sorry for the slow response. I've published a fix for this in the latest release. Please feel free to re-open if the problem persists.

**Closed by michaelgruner** 2023-01-25 22:17 UTC
