### ISSUE TITLE
gstshark not working, datastream and metadata bad?

### ISSUE THREAD

**Issue by tmbuckley** [RidgeRun/gst-shark#69] opened 2020-05-06 20:12 UTC
./gstshark-plot ~/tmp/seattle_tx2/VideoSystem/gstshark_2020-05-06_14:54:50
[warning] Ill-shapen or missing "/* CTF x.y" header for text-only metadata.
[warning] Unsupported CTF specification version 127.0. Trying anyway.
[error] at line 1: token "": syntax error, unexpected $end

[error] Error creating AST
[warning] Unable to open trace metadata for path "/home/tbuckley/tmp/seattle_tx2/VideoSystem/gstshark_2020-05-06_14:54:50".
[warning] [Context] Cannot open_trace of format ctf at path /home/tbuckley/tmp/seattle_tx2/VideoSystem/gstshark_2020-05-06_14:54:50.
[warning] [Context] cannot open trace "/home/tbuckley/tmp/seattle_tx2/VideoSystehark_2020-05-06_14:54:50 for reading.
[error] Cannot open any trace for reading.

[error] opening trace "/home/tbuckley/tmp/seattle_tx2/VideoSystem/gstshark_2020-

[error] none of the specified trace paths could be opened.

**Comment by michaelgruner** [comment] 2020-05-06 20:29
Can you share your trace files?

**Comment by tmbuckley** [comment] 2020-05-06 20:38
this is on a nvidia jetston tx2, gstreamer is 1.14.x your gstshark had version of 0.6.x


files attached. datastream is a ctf file, metadata is empty.


Is there a complete 0.5.x tar file so I can go back a version, I found a 0.5.x.gz but it failed to git the common code in autogen.sh


Terry

________________________________

**Comment by tmbuckley** [comment] 2020-05-07 16:28
?you have some debugging suggestions I can try for you, I really need this to work.

Terry


________________________________

**Comment by tmbuckley** [comment] 2020-05-07 20:25
?since the datastream file is not understood, and the metadata is empty how does gstshark cause these files to be generated.


can I turn on debugging or look at libraries, or other things to help get this to work

Thanks,

Terry


________________________________

**Comment by tmbuckley** [comment] 2020-05-07 21:57
found and compiled babeltrace2 and changed gstshark-plot to use babeltrace2


got this. at least it looks like babeltrace2 is getting farther with the datastream file.


So what am I missing, for tools and libs

Terry



05-07 16:54:53.935 20896 20896 W PLUGIN/SRC.CTF.FS/QUERY support_info_query@query.c:460 cannot append metadata content: metadata-decoder-status=-1
05-07 16:54:53.935 20896 20896 W LIB/QUERY-EXECUTOR bt_query_executor_query@query-executor.c:237 Component class's "query" method failed: query-exec-addr=0x559e878740, cc-addr=0x559e885020, cc-type=SOURCE, cc-name="fs", cc-partial-descr="Read CTF traces from the file sy", cc-is-frozen=0, cc-so-handle-addr=0x559e884480, cc-so-handle-path="/usr/local/lib/babeltrace2/plugins/babeltrace-plugin-ctf.la", object="babeltrace.support-info", params-addr=0x559e889230, params-type=MAP, params-element-count=2, log-level=WARNING
05-07 16:54:53.935 20896 20896 E CLI-CFG-SRC-AUTO-DISC support_info_query_all_sources@autodisc.c:493 babeltrace.support-info query failed.
05-07 16:54:53.935 20896 20896 E CLI main@babeltrace2.c:2645 Command-line error: retcode=1

ERROR:    [Babeltrace CLI] (babeltrace2.c:2645)
  Command-line error: retcode=1
CAUSED BY [Source auto-discovery] (autodisc.c:493)
  babeltrace.support-info query failed.
CAUSED BY [libbabeltrace2] (query-executor.c:237)
  Component class's "query" method failed: query-exec-addr=0x559e878740,
  cc-addr=0x559e885020, cc-type=SOURCE, cc-name="fs", cc-partial-descr="Read CTF
  traces from the file sy", cc-is-frozen=0, cc-so-handle-addr=0x559e884480,
  cc-so-handle-path="/usr/local/lib/babeltrace2/plugins/babeltrace-plugin-ctf.la",
  object="babeltrace.support-info", params-addr=0x559e889230, params-type=MAP,
  params-element-count=2, log-level=WARNING
Loading proctime events...
Loading interlatency events...
Loading scheduling events...
Loading framerate events...
Loading bitrate events...
Loading queuelevel events...
Loading cpuusage events...
Processing proctime...
Processing interlatency...
Processing framerate...
Processing scheduling...
Processing cpusage...
Processing bitrate...
Processing queuelevel...

?


________________________________

**Comment by michaelgruner** [comment] 2020-05-08 15:50
Looking at the trace files, one sec.

**Comment by michaelgruner** [comment] 2020-05-08 15:58
I cannot find the attached trace files any where, I checked the email as well. Can you please send them over again?

On the other hand, please share the following:
* your `gst-launch` pipeline
* the output of running the pipeline with `GST_DEBUG=2`

**Comment by tmbuckley** [comment] 2020-05-08 16:01
metadata is empty.

attached datastream.


My gst-launch is very complicated.

What are you looking for in the? gst_debug-2

thanks

terry


________________________________

**Comment by tmbuckley** [comment] 2020-05-08 16:10
​this has my command line also


this is the output from GST_DEBUG=3 running my system


Terry


Opened database successfully
"main.cpp                   [  51] main()                    :" prebuffer size is:  150
"main.cpp                   [  62] main()                    :" stalkerTakePicMem  0x7fa8c56000
"main.cpp                   [  63] main()                    :" stalkerCreateVideoMem  0x7fa8c55000
"main.cpp                   [  64] main()                    :" stalkerVideoSystemMem  0x7fa8c54000
"mainwindow.cpp             [  16] MainWindow()              :" this  MainWindow(0x7fe767d850)
"mainwindow.cpp             [  17] MainWindow()              :" ui  0x55aef05a40
"mainwindow.cpp             [  18] MainWindow()              :" instance  MainWindow(0x7fe767d850)
"videosystem.cpp            [ 158] run()                     :"
"videosystem.cpp            [ 166] run()                     :" received data
"videosystem.cpp            [ 138] processBuf()              :" CMDVIDEOSTART
"gstinterface.cpp           [ 137] GstInterface()            :" GstInterface
"gstinterface.cpp           [ 152] InitGst()                 :" initGst mPipeline 0x0
"gstinterface.cpp           [ 170] InitGst()                 :" initGst
"gstinterface.cpp           [ 172] InitGst()                 :" initGst
message:  len 0x32
  0000  01 01 08 00 00 00 00 00 00 00 00 00 00 00 00 00  ................

InitGst(259) CMDLINE nvarguscamerasrc ! video/x-raw(memory:NVMM),width=3864,height=2180,format=NV12 ! nvvidconv ! video/x-raw,format=BGRx ! clockoverlay font-desc="calibri 20px" color=0xFF0000FF time-format="%D %H:%M:%S" halignment=right ! gdkpixbufoverlay name=logo  location="/usr/local/stalker/Logo-500x3.svg" ! gdkpixbufoverlay name=retical location="/usr/local/stalker/crosshair-500x3.svg" ! textoverlay name=text font-desc="calibri 20px" color=0xFF0000FF  valignment=top halignment=left xpad=0 ypad=100 text="50.5 MPH  300.0 FT" ! queue  ! tee name=t ! queue  t. ! queue     ! nveglglessink name=displaySink async=false sync=false t. ! queue     ! stalkertakepicture ! nvjpegenc ! multifilesink name=stalkerPicture async=false location=/usr/local/stalker/tmp/Stalker_%05d.jpg t. ! queue     ! nvvidconv ! video/x-raw(memory:NVMM),width=(int)1920,height=(int)1080,format=(string)I420    ! queue     ! nvv4l2h264enc  ! h264parse    ! stalkercreatevideo  name=stalkercreatevideo    ! splitmuxsink name=stalkerVideoSink async-handling=true location=/tmp/tmpFile
../gst-plugin/src/gststalkertakepicture.c(163) CORRECT INIT PLACE 0x7fa8c53000
gst_stalkercreatevideo_init(159)
InitGst(262) mPipeline 0x55af2f0170
InitGst(285) logo 0x55af294190
Opened database successfully
Opened database successfully
"gstinterface.cpp           [  40] getRetical()              :" reticalType is:  0
"gstinterface.cpp           [  41] getRetical()              :" reticleSize is:  500
InitGst(304) retical 0x55af2a1c30
Opened database successfully
"gstinterface.cpp           [ 703] UpdateText()              :" textLocation is:  0
UpdateText(708) textOverlayImagel 0x55af286410
"gstinterface.cpp           [ 741] UpdateText()              :" No data in videoText
InitGst(315) showSink 0x55af0f05c0

Using winsys: x11
0:00:00.200401983 [333m17492[00m   0x55aee95520 [33;01mWARN   [00m [00m                v4l2 gstv4l2object.c:2370:gst_v4l2_object_add_interlace_mode:0x55af2dfef0[00m Failed to determine interlace mode
0:00:00.200556386 [333m17492[00m   0x55aee95520 [33;01mWARN   [00m [00m                v4l2 gstv4l2object.c:2370:gst_v4l2_object_add_interlace_mode:0x55af2dfef0[00m Failed to determine interlace mode
0:00:00.200657443 [333m17492[00m   0x55aee95520 [33;01mWARN   [00m [00m                v4l2 gstv4l2object.c:2370:gst_v4l2_object_add_interlace_mode:0x55af2dfef0[00m Failed to determine interlace mode
0:00:00.200915591 [333m17492[00m   0x55aee95520 [33;01mWARN   [00m [00m                v4l2 gstv4l2object.c:4408:gst_v4l2_object_probe_caps:<nvv4l2h264enc0:src>[00m Failed to probe pixel aspect ratio with VIDIOC_CROPCAP: Unknown error -1
"mainwindow.cpp             [  44] VideoStart()              :" gst.Init returned true
0:00:00.218374014 [333m17492[00m   0x55af3065e0 [32;01mFIXME  [00m [00;04m             default gstutils.c:3981:gst_pad_create_stream_id_internal:<nvarguscamerasrc0:src>[00m Creating random stream-id, consider implementing a deterministic way of creating a stream-id
NvMMLiteOpen : Block : BlockType = 4
===== NVMEDIA: NVENC =====
NvMMLiteBlockCreate : Block : BlockType = 4
0:00:00.236854309 [333m17492[00m   0x55af3068f0 [33;01mWARN   [00m [00m      v4l2bufferpool gstv4l2bufferpool.c:1062:gst_v4l2_buffer_pool_start:<nvv4l2h264enc0:pool:src>[00m Uncertain or not enough buffers, enabling copy threshold
H264: Profile = 66, Level = 0
0:00:01.269429015 [333m17492[00m   0x7f6c003ca0 [33;01mWARN   [00m [00m      v4l2bufferpool gstv4l2bufferpool.c:1526:gst_v4l2_buffer_pool_dqbuf:<nvv4l2h264enc0:pool:src>[00m Driver should never set v4l2_buffer.field to ANY

​


________________________________

**Comment by michaelgruner** [comment] 2020-05-08 16:10
Mostly to see if tracers are printing any errors. Do simpler pipelines work? this can tell us if it's something in the environment or in the pipeline (a bug in gst-shark)

**Comment by tmbuckley** [comment] 2020-05-08 16:21
?new debug output file,

Terry


________________________________

**Comment by michaelgruner** [comment] 2020-05-08 16:21
Please try this pipeline and see if the generated trace files are valid:

`GST_TRACERS=proctime gst-launch-1.0 videotestsrc ! identity ! fakesink sync=true`

**Comment by michaelgruner** [comment] 2020-05-08 16:24
FYI, if you are attaching files, I cannot see them anywhere.

**Comment by tmbuckley** [comment] 2020-05-08 16:33
?need a better way to share files.


Need to take a break , will try to get more data for you in an hour.


gst-shark-plot did not throw any errors on the videotestsrc line you sent, but there was no plot either.


Terry


________________________________

**Comment by tmbuckley** [comment] 2020-05-08 18:11
?so it looks like your test line works, and my multi "t" multi-thread and multi-processor environment caused the datastream file to be corrupted.


too many processes writing to the datastream and missing syncs, for flushes?


Can I try anything else to get you more info?


Thanks,

Terry

________________________________

**Comment by tmbuckley** [comment] 2020-05-08 18:13
?my brief looking at the cft.c I think I remember parts being written without any locks between cores/threads/processes.


________________________________

**Comment by tmbuckley** [comment] 2020-05-08 18:23
GST_TRACERS=cpuusage gst-launch-1.0 videotestsrc ! identity ! fakesink sync=true?


did not generate a datastream or metadata file.


Thanks,

Terry


________________________________

**Comment by michaelgruner** [comment] 2020-05-08 18:30
Ah, good catch. Let me check.

**Comment by tmbuckley** [comment] 2020-05-08 18:31
?thank you,


Terry


________________________________

**Comment by michaelgruner** [comment] 2020-05-09 04:22
I tested a somewhat similar pipe to yours in my laptop (see below). I didn't get the same problem, but I did get a segfault when using the `interlatency` plugin. The cause was an unlinked pipe in the pipe which we didn't handle.

`text="50.5 MPH  300.0 FT" ! queue  ! tee name=t ! ****queue****  t. ! queue     ! `

I'm thinking this could be the reason your trace files were corrupted. Can you try the following branch `hotfix/interlatency-segfault-on-unlinked-pads` and see if you get a different result?

Here's the full pipe based on yours:
```
GST_TRACERS="proctime;scheduletime;interlatency;framerate;queuelevel;bitrate;buffer" gst-launch-1.0 avfvideosrc ! video/x-raw,width=1280,height=720,format=NV12 ! videoconvert ! video/x-raw,format=BGRx ! clockoverlay font-desc="calibri 20px" color=0xFF0000FF time-format="%D %H:%M:%S" halignment=right ! gdkpixbufoverlay name=logo  location="crosshair.svg" ! gdkpixbufoverlay name=retical location="crosshair.svg" ! textoverlay name=text font-desc="calibri 20px" color=0xFF0000FF  valignment=top halignment=left xpad=0 ypad=100 text="50.5 MPH  300.0 FT" ! queue  ! tee name=t ! queue  t. ! queue     ! glimagesink async=false sync=false t. ! queue     ! jpegenc ! multifilesink name=stalkerPicture async=false location=/tmp/Stalker.jpg t. ! queue  ! videoconvert ! videoscale ! video/x-raw,width=1920,height=1080,format=I420    ! queue     ! x264enc  ! h264parse    ! splitmuxsink name=stalkerVideoSink async-handling=true location=/tmp/tmpFile
```

**Comment by tmbuckley** [comment] 2020-05-11 14:08
did a git pull origin hotfix/interlatency-segfault-on-unlinked-pads?

make; sudo make install


my test did not run, it just hangs, added gdb and nothing is crashing, only no video.


Terry


________________________________

**Comment by tmbuckley** [comment] 2020-05-11 16:08
?debugging pointers? Tried gdb, nothing died, but my stream is hung


Terry


________________________________

**Comment by michaelgruner** [comment] 2020-05-11 16:13
I don’t think the tracers can hang your stream. Can you look for anything off when running with GST_DEBUG=2? I’m very suspicious of that unlinked pad you have on your pipeline.

**Comment by tmbuckley** [comment] 2020-05-11 16:18
?add the tracer stuff and my app hangs, remove tracer stuff app runs and displays video.


Please help me debug this, really need to determine cpuusage  for cleanup.


Terry


________________________________

**Comment by michaelgruner** [comment] 2020-05-11 16:22
Let me have someone try your pipe on a Jetson.

**Comment by tmbuckley** [comment] 2020-05-13 17:37
​Is there a place or FAQ on debugging gstshark?


I can do things to figure out what is happening, how do I get info out of the stream to figure out why gstshark is killing my gstreamer app.


Thanks,

Terry


________________________________

**Comment by michaelgruner** [comment] 2020-05-13 20:54
So I'm unable to reproduce your problem using a similar pipe to yours on my PC.  @maumonteroj is reproducing your pipe on a TX2. @maumonteroj do you have any updates?

**Comment by michaelgruner** [comment] 2020-05-13 20:54
@tmbuckley does this happen with any tracer or just CPU usage?

**Comment by maumonteroj** [comment] 2020-05-14 01:48
Hi @tmbuckley, I was able to reproduce your issue in my tx2, we are going to continue checking how to solve it.

**Comment by maumonteroj** [comment] 2020-05-20 00:28
Hi @tmbuckley , we found that the issue is because your pipeline is not closing properly. In order to close I need to force the teardown and for that reason, the pending file flushes are not made it and the files get corrupted or empty.

I made a branch for you to test in order to see if this is the same issue you are experimenting. Can you please try the test/disable-file-buffering branch and see if you get a different result?

We are going to evaluate make this solution a configurable variable.

**Comment by alehed** [comment] 2020-06-05 13:09
Hey @maumonteroj, thanks a lot for the branch! I was having the same issue. Compiling gst-shark from the branch fixed it for me.

**Comment by compiaffe** [comment] 2020-07-07 15:29
@maumonteroj I also had that issue. Using the test/disable-file-buffering branch fixed it for me, too.

**Comment by michaelgruner** [comment] 2020-07-07 15:38
Thanks all for the confirmation, I'll close this issue. We're making a release later this week with a few improvements, including this one.

**Closed by michaelgruner** 2020-07-07 15:38 UTC
